name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # YARN
      - name: Yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Yarn ESLint
        uses: borales/actions-yarn@v4
        with:
          cmd: lint 
      - name: Yarn build Webpack
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: Yarn Jest
        uses: borales/actions-yarn@v4
        with:
          cmd: test:jest

      # - name: Build
      #   run: |
      #     npm install
      #     npm run build
